parent='/home/ashiver/Documents/EMAP/chemical_screen_data/data_camera_iris/';
home={'RNAP1/','RNAP1/','RNAP1/','RNAP1/','RNAP2/','RNAP2/','RNAP2/','RNAP2/'};
data='0.9.4_iris/';
condition={'r1b1.csv','r1b2.csv','r1b3.csv','r1b4.csv','r2b1.csv','r2b2.csv','r2b3.csv','r2b4.csv'};
array={'R1_key.csv','R1_key.csv','R1_key.csv','R1_key.csv','R2_key.csv','R2_key.csv','R2_key.csv','R2_key.csv'};
structurekey={'a1','a2','a3','a4','b1','b2','b3','b4'};    
for rnap = 1 : 4
    key=structurekey{rnap};
[score.(key),meta.(key),scoremat.(key),datameta.(key),datamatV.(key)...
        datamatN.(key),datamatS.(key),datamatF.(key),datamat.(key),...
        model.(key)]=scoreRNAP([parent,home{rnap},condition{rnap}],...
                                [parent,home{rnap},array{rnap}],...
                                [parent,home{rnap},data],...
                                'iris_v0_ecoopacity',r1i,r1b);
end
for rnap = 5 : 8
    key=structurekey{rnap};
[score.(key),meta.(key),scoremat.(key),datameta.(key),datamatV.(key)...
        datamatN.(key),datamatS.(key),datamatF.(key),datamat.(key),...
        model.(key)]=scoreRNAP([parent,home{rnap},condition{rnap}],...
                                [parent,home{rnap},array{rnap}],...
                                [parent,home{rnap},data],...
                                'iris_v0_ecoopacity',r2i,r2b);
end