parent='/home/ashiver/Documents/EMAP/chemical_screen_data/data_camera_iris/';
home={'KEIO1/','KEIO2/','KEIO3/','KEIO4/','KEIO5/','KEIO6/'};
data='0.9.4_iris/';
condition1={'k1_new.csv','k2_new.csv','k3_new.csv','k4_new.csv','k5_new.csv','k6_new.csv'};
array={'KEIO1_KEY.csv','KEIO2_KEY.csv','KEIO3_KEY.csv','KEIO4_KEY.csv','KEIO5_KEY.csv','KEIO6_KEY.csv'};
structurekey={'p1','p2','p3','p4','p5','p6'};
    
for keio = 1 : 5
    key=structurekey{keio};
    [~,~,~,datameta.(key),datamatV.(key)...
        ~,~,~,~,...
        ~]=scoreKEIO([parent,home{keio},condition1{keio}],...
                                [parent,home{keio},array{keio}],...
                                [parent,home{keio},data],...
                                'iris_v0_ecoopacity',{},[],'keio',[]);
end

keio=6;
key=structurekey{keio};
[~,~,~,datameta.(key),datamatV.(key)...
        ~,~,~,~,...
        ~]=scoreKEIO([parent,home{keio},condition1{keio}],...
                                [parent,home{keio},array{keio}],...
                                [parent,home{keio},data],...
                                'iris_v0_ecoopacity',{},[],'keio6',keio6ind);