parent='/home/ashiver/Documents/EMAP/chemical_screen_data/data_phenomics_iris/';
data='George_set_4120/';
condition1={'p1_4120krit.csv','p2_4120krit.csv','p3_4120krit.csv','p4_4120krit.csv','p5_4120krit.csv','p6_4120krit.csv'};
array={'KEIO1_KEY.csv','KEIO2_KEY.csv','KEIO3_KEY.csv','KEIO4_KEY.csv','KEIO5_KEY.csv','KEIO6_KEY.csv'};
structurekey={'p1','p2','p3','p4','p5','p6'};
    
for keio = 1 : 5 
    key=structurekey{keio};
    [scoremat.(key),datametaC.(key),datamatC.(key),datameta.(key),datamatV.(key),...
        datamatN.(key),datamatS.(key),datamatF.(key),datamat.(key),...
        model.(key)]=scorePHEN([parent,condition1{keio}],...
                                [parent, array{keio}],...
                                [parent, data],...
                                'krit_dat',{},[],'keio',[]);
end

keio=6;
key=structurekey{6};
[scoremat.(key),datametaC.(key),datamatC.(key),datameta.(key),datamatV.(key),...
        datamatN.(key),datamatS.(key),datamatF.(key),datamat.(key),...
        model.(key)]=scorePHEN([parent,condition1{keio}],...
                                [parent,array{keio}],...
                                [parent,data],...
                               'krit_dat',{},[],'keio6',keio6ind);
save('/home/ashiver/Desktop/krit4120_georgefiles.mat');
exit;