parent='/Users/ashiver/Documents/Papers/CAG/RNAP_paper/KRIT_data/';
data='iris/';
condition={'p1_4120krit.csv','p2_4120krit.csv','p3_4120krit.csv','p4_4120krit.csv','p5_4120krit.csv','p6_4120krit.csv'};
array={'KEIO1_KEY.csv','KEIO2_KEY.csv','KEIO3_KEY.csv','KEIO4_KEY.csv','KEIO5_KEY.csv','KEIO6_KEY.csv'};
structurekey={'p1','p2','p3','p4','p5','p6'};
    
for keio = 1 : 5 
    key=structurekey{keio};
    [scoremat.(key),datametaC.(key),datamatC.(key),datameta.(key),datamatV.(key),...
        datamatN.(key),datamatS.(key),datamatF.(key),datamat.(key),...
        settings.(key)]=scorePHEN([parent,condition{keio}],...
                                [parent,array{keio}],...
                                [parent,data],...
                                'krit_dat',{},[],'keio',[]);
end

keio=6;
key=structurekey{keio};
[scoremat.(key),datametaC.(key),datamatC.(key),datameta.(key),datamatV.(key),...
        datamatN.(key),datamatS.(key),datamatF.(key),datamat.(key),...
        settings.(key)]=scorePHEN([parent,condition{keio}],...
                                [parent,array{keio}],...
                                [parent,data],...
                               'krit_dat',{},[],'keio6',keio6ind);