parent='/Users/ashiver/Documents/Papers/CAG/RNAP_paper/KEIO_data/';
data='iris/';
condition={'k1b0.csv','k2b0.csv','k3b0.csv','k4b0.csv','k5b0.csv','k6b0.csv'};
array={'KEIO1.csv','KEIO2.csv','KEIO3.csv','KEIO4.csv','KEIO5.csv','KEIO6.csv'};
structurekey={'p1','p2','p3','p4','p5','p6'};
    
for keio = 1 : 5 
    key=structurekey{keio};
    [scoremat.(key),datametaC.(key),datamatC.(key),datameta.(key),datamatV.(key),...
        datamatN.(key),datamatS.(key),datamatF.(key),datamat.(key),...
        settings.(key)]=scorePHEN([parent,condition{keio}],...
                                [parent,array{keio}],...
                                [parent,data],...
                                'iris_v0_ecoopacity',{},[],'keio',[]);
end

keio=6;
key=structurekey{keio};
[scoremat.(key),datametaC.(key),datamatC.(key),datameta.(key),datamatV.(key),...
        datamatN.(key),datamatS.(key),datamatF.(key),datamat.(key),...
        settings.(key)]=scorePHEN([parent,condition{keio}],...
                                [parent,array{keio}],...
                                [parent,data],...
                               'iris_v0_ecoopacity',{},[],'keio6',keio6ind);
